#!/bin/sh

indent() {
  sed -u 's/^/       /'
}

echo "-----> Install vim 7.3"
BUILD_DIR=$1

DOWNLOAD_URL="https://s3.amazonaws.com/bengoa/vim-static.tar.gz"
cd $BUILD_DIR

echo "DOWNLOAD_URL = " $DOWNLOAD_URL | indent
mkdir vim

curl 'https://s3.amazonaws.com/bengoa/vim-static.tar.gz' | tar -xz -C vim


echo "exporting PATH and LIBRARY_PATH" | indent
PROFILE_PATH="$BUILD_DIR/.profile.d/vim73.sh"
mkdir -p $(dirname $PROFILE_PATH)
echo 'export VIMRUNTIME="$HOME/vim/runtime"' >> $PROFILE_PATH
echo 'export PATH="$HOME/vim:$PATH"' >> $PROFILE_PATH
